language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coverage
script: coverage run --source=singleton_decorator setup.py test
after_success:
  - pip install coveralls
  - coveralls
